FROM adoptopenjdk/openjdk8:x86_64-alpine-jre8u232-b09

ENV CATALINA_HOME /opt/tomcat
ENV PATH $CATALINA_HOME/bin:$CATALINA_HOME/app:$PATH
WORKDIR $CATALINA_HOME

ENV TOMCAT_SHA512 4e69f9e6c72219e70a5a9f2046ba58732cfd667329712a4a675102ce6286c5ad59399eb0e5ea5d7973305443c3a7987789689e5ce0193729c0b9373424fffea8

ENV TOMCAT_TAR="apache-tomcat-8.5.50-embed.tar.gz"

COPY "embed/$TOMCAT_TAR" "$CATALINA_HOME/"
COPY app/webapp1.sh app/startup.jar app/webapp1.jar "$CATALINA_HOME/app/"

RUN set -eux && \
    addgroup -g 91 -S tomcat && \
    adduser -u 91 -S -G tomcat tomcat && \
    mkdir -p "$CATALINA_HOME/lib" && \
    echo "$TOMCAT_SHA512  $TOMCAT_TAR" | sha512sum -c - && \
    tar -xf "$TOMCAT_TAR" --strip-components=1 -C "$CATALINA_HOME/lib" && \
    chown -R tomcat.tomcat "$CATALINA_HOME" && \
    chmod +x app/*.sh

EXPOSE 8080
CMD [ "webapp1.sh" ]
